### ISSUE TITLE
feat: finish all the TODO in `index.jsx`

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/scaffold-aptos#23]
`Money`: 150U

**Comment by Blockchain-Key** [comment]
🙋🏻‍♀️

**Comment by aboutmydreams** [comment]
where is todo ?

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/34613360/224874801-06feed9e-4682-4cb7-a06a-24a859ee042f.png">
