### ISSUE TITLE
feat/ optimize the static resource path for deployment.

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/scaffold-aptos#28]

**Comment by Iamknownasfesal** [comment]
Can you explain the optimization or what to optimize?

**Comment by leeduckgo** [comment]
> Can you explain the optimization or what to optimize?

It have already done, because we found the static resource not shown proper when deploy to the prod env.

If you interest in this project, we could talk on telegram: @leeduckgo .

**Comment by bugradursun** [comment]
I am interested in your project. can I contact you via discord?

**Comment by leeduckgo** [comment]
> I am interested in your project. can I contact you via discord?

Yes, my discord is "hitchhacker #3006", but I am not check my discord often, so it is better to contact me by the telegram or the email: "leeduckgo@gmail.com"
