### ISSUE TITLE
feat/create atpos dapp by npx.

### ISSUE THREAD

**Issue by leeduckgo** [NonceGeek/scaffold-aptos#30]
`money`: 100 `USDT`

**Comment by 0xjusta** [comment]
https://www.npmjs.com/package/create-apt-app

**Comment by leeduckgo** [comment]
Done! see in:

> https://github.com/rootMUD/create-move-dapp

**Comment by leeduckgo** [comment]
https://bscscan.com/address/0x76CCE52cbB91ea534532DdD67842727fe8Eaa39B
